extends Node
var text1_1 = "Here we go, today is the day, we're going to find it."
var text1_2 = "I hope you are not mistaken, our funds are getting low."
var text2_1 = "We can't see anything, let's start the sonar."
var text2_2 = "Roger that."
var text3_1 = "Look at that wreck, I knew we were on the right track."
var text3_2 = "Not what we're looking for though, let's keep going."
var text4_1 = "Are you sure we can fit through? this is narrow."
var text4_2 = "Don't be a wimp, it's fine Jean."
var text5_1_1 = "We're deep enough, let me plug the living matter detector."
var text5_2_1 = "damn, that's close, let's keep going."
var text6_1 = "Are you sure you want to continue? that was already quite difficult."
var text6_2 = "Yes, we can't stop there."
var text7_1_1 = "It's... It's a dead end."
var text7_1_2 = "Wait, have you seen that?"
var text7_2_1 = "Atlantis!"
var text7_2_2 = "It's incredible, better than a treasure! we need to go back up, Tell everyone about it."
var text7_2_3 = "Yes, let's do that, wait... do you hear that?"
